name: Machinery
version: 1.0
main: me.oriharel.machinery.Machinery
api-version: 1.13
depend: [MultiEconomy, WorldEdit, CustomRecipes, ProtocolLib]
authors: [Heknon]
description: Adds machines to the game
website: oriharel.me
load: POSTWORLD